//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForceOfWillCube.Utils {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppStrings() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ForceOfWillCube.Utils.AppStrings", typeof(AppStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Bad!.
        /// </summary>
        internal static string Bad {
            get {
                return ResourceManager.GetString("Bad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Bad done, bad job..
        /// </summary>
        internal static string BadDone {
            get {
                return ResourceManager.GetString("BadDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a You have correctly deleted the collection..
        /// </summary>
        internal static string CorrectlyDeleteCollection {
            get {
                return ResourceManager.GetString("CorrectlyDeleteCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Delete Collection.
        /// </summary>
        internal static string DeleteCollection {
            get {
                return ResourceManager.GetString("DeleteCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Great!.
        /// </summary>
        internal static string Great {
            get {
                return ResourceManager.GetString("Great", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Input the name of the new collection.
        /// </summary>
        internal static string InputCollectionName {
            get {
                return ResourceManager.GetString("InputCollectionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Main Page.
        /// </summary>
        internal static string MainPageTitle {
            get {
                return ResourceManager.GetString("MainPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a New Collection.
        /// </summary>
        internal static string NewCollection {
            get {
                return ResourceManager.GetString("NewCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ok.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a USER_NOT_SIGN_IN.
        /// </summary>
        internal static string USER_NOT_SIGN_IN {
            get {
                return ResourceManager.GetString("USER_NOT_SIGN_IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a USER_NOT_SIGN_OUT.
        /// </summary>
        internal static string USER_NOT_SIGN_OUT {
            get {
                return ResourceManager.GetString("USER_NOT_SIGN_OUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a USER_SIGN_IN.
        /// </summary>
        internal static string USER_SIGN_IN {
            get {
                return ResourceManager.GetString("USER_SIGN_IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a USER_SIGN_OUT.
        /// </summary>
        internal static string USER_SIGN_OUT {
            get {
                return ResourceManager.GetString("USER_SIGN_OUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Well done, good job..
        /// </summary>
        internal static string WellDone {
            get {
                return ResourceManager.GetString("WellDone", resourceCulture);
            }
        }
    }
}
